# Base image
FROM node:18-alpine

# Create app directory
WORKDIR /usr/src/app

# copy package.json, package-lock.json into image
COPY package*.json ./

# Install app dependencies
RUN npm install

# Bundle app source
COPY . .

# Creates a "dist" folder with the production build
RUN npm run build

#port of container
EXPOSE 8080

# Start the server using the production build
CMD [ "npm", "run", "start:prod" ]